version: '3.4'
services:
  chat:
    image: urmoonfriend/chat_pet:0.0.1
    container_name: chat
    ports:
      - "58087:8081"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://chat_db_container:5432/chat_db
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
    depends_on:
      - chat_db_container
    restart: always
  chat_db_container:
    image: postgres
    container_name: chat_db_container
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=chat_db
    volumes:
      - /var/lib/docker/containers/booking/db/data:/var/lib/postgresql/data

